@startuml
left to right direction
skinparam packageStyle rectangle
actor customer
rectangle Overview {
  customer -- (login)
  (show error) .> (login) : <<extend>>
  (login) .> (check\nusername/password) : <<include>>
  (check\nusername/password) .> (dashboard) : <<include>>
  customer -- (logout)
}
@enduml