	@startuml
left to right direction
skinparam packageStyle rectangle
actor customer
actor mailServer
rectangle Account-AccountSettings {
  customer -- (sign up)
  (sign up) .> (notify user) : <<include>>
  (notify user) -- mailServer

  customer -- (change password)
  (change\npassword) .> (notify user) : <<include>>

  customer -- (update\naccount detail)
  customer -- (enable/disable\ntwo-factor authentication)
  customer -- (generate\napi access token)
  customer -- (reset\napi access token)
  customer -- (logout)

  customer -- (sign in)
  (sign in) .> (check\nusername/password) : <<include>>
  (show error) .> (login) : <<extends>>
}
@enduml