	@startuml
left to right direction
skinparam packageStyle rectangle
actor customer
rectangle Account-AbuseCases {
  customer -- (generate auto\nData Processing Agreement)
  (generate auto\nData Processing Agreement) .> (accept Data Processing Agreement) : <<include>>
  (update account detail) .> (generate auto\nData Processing Agreement) : <<extend>>
}
@enduml