@startmindmap
'https://plantuml.com/mindmap-diagram

caption Multi-CDN Architecture Portal Admin

* Admin

** NS1
*** Disaster recovery and high availability
*** Multi CDN management
*** Service discovery
*** Multi-cloud orchestration
*** DNS security
*** DevOps and Automation
*** DNS global server load balancing
*** Redundant and secondary DNS

** Atanar
*** Limit Redirects
*** Javascript performance tuning
*** HTML complexity
*** Increase capability
*** Better resource management
*** Hosting
*** Front End Optimization
*** CDN Audit
*** DNS Routing
*** Streaming (Live video or on-demand)
*** SSL Acceleration (https and certificates handling)
*** CDN Cache
*** Supports http delivery

** MetaCDN
*** Detailed Analytics
*** Developer support
*** Credit rollover
*** Low latency
*** Instant Stream Archiving
*** Real-time stats
*** Streamlined workflows
*** Full privacy controls
*** Embeddable chat
*** Live DVR rewind
*** Live highlight clips

** Global Dots
*** 24/7/365 Support
*** Managed Service
*** API Acceleration
*** Accelerate Encrypted Content
*** Device Detection
*** TCP Acceleration
*** Dynamic Site Acceleration
*** Instant Purge
*** SSL
*** Dynamic Caching
*** Static Caching
*** Image Optimization
























center footer tutqq@viettelidc.com.vn
@endmindmap
